#Welcome to the AllItems config! Info is on the bottom of the file.

#############
## GENERAL ##
#############

general:
  global: true
  personal: true
  others_lists: true
  list_priority: 0

  announce_send: false

  progress: true
  check: true
  player: true
  settings: true

  main_completion: true
  personal_completion: true

  auto_save: true

###########
## ITEMS ##
###########

all_items:
  toggle: true

  file: normal

  subtraction: false

  auto_collect: false

##########
## MOBS ##
##########

all_mobs:
  toggle: true

  file: normal

##########
## INFO ##
##########

# "global/personal/others_lists": Allows everyone to see a server-wide list, a personal list, or other personal lists respectively.
# "list_priority": Submission message and itemSubtraction (if enabled) takes priority for global list (0) or personal list (1).

# "announce_send": Toggles whether a send message is sent to just the player, or the whole server

# "progress/check/player/settings": Enables/Disables the respective commands by non-op players

# "main_completion/personal_completion" Sends a completion message to all players if enabled for the main lists or personal lists respectively.

# "toggle": Enables (true)/Disables (false) the respected part of the plugin (if you only wanted items for example).

# "file": Chooses the list to go off of in either ItemLists or MobLists (there are a few there by default, you can use those or make your own).

# "subtraction": Subtracts the item(s) once it is submitted

# "auto_collect": Automatically submits an item once it is picked up by the player

#For any issues please reach out on discord... https://discord.gg/zHzFgWX8KW