name: All_Items
version: 6.0
author: BowserTheBoss
main: xyz.quazaros.main
api-version: 1.17

commands:
  aitem:
    description: Umbrella Command For All Item Related Sub Commands
  amob:
    description: Umbrella Command For All Mob Related Sub Commands
  atime:
    description: Command Used To Set Up The Timer
  areset:
    description: Resets The Plugin
  ahelp:
    description: Help Command For The Whole Plugin

permissions:
  all_items.items:
    description: Will allow players to access the items section of the plugin
    default: true
  all_items.mobs:
    description: Will allow players to access the mobs section of the plugin
    default: true
  all_items.admin:
    description: Will allow players to access the admin commands
    default: op

softdepend: ['PlaceholderAPI']
